"""Fix db errors

Revision ID: 44668e30d67c
Revises: 2c4a21f07dcd
Create Date: 2024-09-04 13:54:02.552643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44668e30d67c'
down_revision = '2c4a21f07dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('companies_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('companies_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
