"""Adds validates_model_input_datetime method to model_helpers.py and finishes validations for incident.py and near_miss.py

Revision ID: a19a44c12eea
Revises: b29a7027dfad
Create Date: 2024-09-01 11:01:38.255772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a19a44c12eea'
down_revision = 'b29a7027dfad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('report_time', sa.DateTime(), nullable=False))
        batch_op.drop_column('incident_report_date')
        batch_op.drop_column('incident_report_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incident_report_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('incident_report_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('report_time')
        batch_op.drop_column('report_date')

    # ### end Alembic commands ###
