"""Adds more tables

Revision ID: b35694fc3c29
Revises: 14117fbb8030
Create Date: 2024-08-26 14:46:00.595293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35694fc3c29'
down_revision = '14117fbb8030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('injury_description', sa.String(length=260), nullable=True),
    sa.Column('incident_date', sa.DateTime(), nullable=False),
    sa.Column('incident_time', sa.DateTime(), nullable=False),
    sa.Column('incident_report_date', sa.DateTime(), nullable=False),
    sa.Column('incident_report_time', sa.DateTime(), nullable=False),
    sa.Column('mechansim_of_injury', sa.String(length=260), nullable=False),
    sa.Column('body_part_injured', sa.String(length=260), nullable=False),
    sa.Column('symptoms', sa.String(length=260), nullable=False),
    sa.Column('incident_location', sa.String(length=100), nullable=False),
    sa.Column('risk_assessment_severity', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_probability', sa.Integer(), nullable=False),
    sa.Column('first_aid_given', sa.Boolean(), nullable=False),
    sa.Column('first_aid_details', sa.String(length=260), nullable=False),
    sa.Column('recovery_status', sa.String(length=260), nullable=False),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=260), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    op.drop_table('incidents')
    op.drop_table('employees')
    # ### end Alembic commands ###
